---
title: "Data Aggregation Introduction"
author: "Owen Ouyang"
date: "`r format(Sys.Date())`"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(data.table)
library(tidyverse)
library(rebus)
library(ggrepel)
library(ggthemes)
library(plotly)
library(scales)
library(DT)
library(highcharter)
library(skimr)
library(leaflet)
library(leaflet.extras)
library(ggmap)
library(htmltools)
library(flexdashboard)
library(readr)
library(lubridate)
library(knitr)
library(skimr)
library(GGally)
library(viridis)

energyData <- read_csv("input/PUB_PriceHOEPPredispOR.csv")%>% 
  mutate(Date=mdy(Date))
colnames(energyData) <- colnames(energyData) %>% str_replace(pattern = " ", replacement = "_")

retail_df <- read_csv('input/retail promo data.csv')
```


Energy Market Dataset Overview
=====================================


Column {data-width=550}
-----------------------------------------------------------------------

### Interactive Data Table

```{r}

datatable(
  energyData, rownames = FALSE,
  extensions = 'Buttons', options = list(
    dom = 'Bfrtip',
    buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
  )
)


```


Column {data-width=450}
-----------------------------------------------------------------------

### Statistic Overview{data-height=200}
```{r}
summary(energyData[,3:5])

```

### Monthly Stats


```{r}
energyMonthlyData <- energyData %>% 
  mutate( Month=months(Date), Total_Cost=HOEP*Ontario_Demand, MonthIndex=match(Month, month.name)) %>%
  group_by(Month, MonthIndex) %>%
  summarise(Max_Demand=max(Ontario_Demand), Usage=sum(Ontario_Demand), Cost=sum(Total_Cost) ) %>%
  arrange(MonthIndex) %>% 
  select(-MonthIndex) 
energyMonthlyData %>% 
  kable()

```


Energy Market Data Visualization
=====================================

Column {data-width=500}
-----------------------------------------------------------------------

### Interactive Drill Down

```{r}
energyMonthlyDataResult <- energyMonthlyData %>% gather(key = "Key", value = "Value", -Month)



df1 <- energyMonthlyDataResult %>% 
  group_by(name = Key, drilldown = Key) %>% 
  summarise(y = n()) %>% 
  arrange(desc(y))

df2 <- energyMonthlyDataResult %>% 
  group_by(Key, Month) %>% 
  mutate(y = Value, colorByPoint = 1) %>% 
  # arrange(desc(y)) %>%
  group_by(name = Key, id = Key
           # , colorByPoint
  ) %>% 
  do(data = list_parse(
    mutate(., name = Month, drilldown = tolower(paste(Key, Month, sep=": "))) %>% mutate(month_index=match(Month, month.name)) %>%  
      group_by(name, drilldown, month_index) %>% 
      summarise(y=Value) %>% 
      arrange(month_index) %>%
      select(name, y, drilldown))) 
    # %>% arrange(desc(y)))) 

a <- highchart() %>% 
  hc_chart(type = 'pie') %>% 
  hc_xAxis(type = "category") %>% 
  hc_add_series(name = 'number of months', data = df1
                # , colorByPoint = 1
  ) %>% 
  hc_drilldown(
    allowPointDrilldown = TRUE,
    series =list_parse(df2)
  ) %>%
  hc_legend(enabled = F) %>% 
  hc_title(text = "Key Value Pie Chart") %>% 
  hc_add_theme(hc_theme_google())


b <- highchart() %>% 
  hc_chart(type = 'bar') %>% 
  hc_xAxis(type = "category") %>% 
  hc_add_series(name = 'number of months', data = df1, colorByPoint = 1) %>% 
  hc_drilldown(
    allowPointDrilldown = TRUE,
    series =list_parse(df2)
  ) %>%
  hc_legend(enabled = F) %>% 
  hc_title(text = "Key Value Bar Chart") %>% 
  hc_add_theme(hc_theme_google())
rm(df1, df2)



lst <- list(
  a,
  b
)

hw_grid(lst, rowheight = 400)
rm(a, b, lst)



```


Column {data-width=500}
-----------------------------------------------------------------------

### 3D Visulization{data-height=700}
```{r}

energyData %>% 
  plot_ly(x=~HOEP,y=~Market_Demand,z= ~Ontario_Demand, hoverinfo = 'text', colors = viridis(15),
           text = ~paste(
                         '<br>HOEP:', HOEP,
                         '<br>Market_Demand:', Market_Demand,
                         '<br>Ontario_Demand:', Ontario_Demand
                        )) %>% 
  add_markers(opacity = 0.8) %>%
  layout(title = "Key Variables",
         annotations=list(yref='paper',xref="paper",y=1.05,x=1.1, text="Comparison",showarrow=F),
         scene = list(xaxis = list(title = 'HOEP'),
                      yaxis = list(title = 'Market Demand'),
                      zaxis = list(title = 'Ontario Demand')))
```

<!-- ### GGPairs -->


<!-- ```{r} -->
<!-- energyData %>% gather(key = "Key", value = "Value",-c(Date,Hour,HOEP)) %>%  -->
<!--   ggpairs(aes(col=Key,alpha=.3)) -->





<!-- ``` -->


Promotion Strategy Case Study
=====================================

Column {data-width=650}
-----------------------------------------------------------------------

### Interactive Data Table

```{r}


datatable(
  retail_df, rownames = FALSE,
  extensions = 'Buttons', options = list(
    dom = 'Bfrtip',
    buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
  )
)


```


Column {data-width=350}
-----------------------------------------------------------------------

### Statistic Overview{data-height=500}
```{r}

retail_df %>% skim() %>% kable()


```

### % Short Trips


```{r}
library(corrplot)





```